### ISSUE TITLE
Invalid injectionSelector key?

### ISSUE THREAD

**Issue by pchaigno** [cdibbs/language-jison#17]
Is the `injectionSelector` key serving any purpose? It's detected as invalid on GitHub.com and throwing errors (see github/linguist#3924 for further details).

**Comment by nwhetsell** [comment]
I’m assuming you mean

https://github.com/cdibbs/language-jison/blob/0e897be16c5a159921acfb7f3e4afc751139aede/grammars/jisonlex-injection.cson#L22

The purpose of that is to scope built-in Jison Lex variables in JavaScript code as `variable.language.jisonlex` in both Jison Lex and Jison files.

For example, this snippet from a Jison file contains the Jison Lex variable `yytext`:

https://github.com/cdibbs/language-jison/blob/0e897be16c5a159921acfb7f3e4afc751139aede/spec/sample.jison#L9

`yytext` is not highlighted on GitHub, but it is highlighted in [Atom](https://atom.io).

**Comment by pchaigno** [comment]
Ok, I see. Thanks for the explanation and the quick answer!
I'll whitelist the `injectionSelector` key in the compiler. By the way, do you know where I could find documentation on `injectionSelector`?

**Comment by nwhetsell** [comment]
No, unfortunately. There are test fixtures for `injectionSelector` in [atom/first-mate](https://github.com/atom/first-mate) (like [this](https://github.com/atom/first-mate/blob/4216f7d7248f651d44a015a386dbc9a286891048/spec/fixtures/normal-injection-selector.cson)), so someone over there may know. I also don’t remember how I figured out how to use `injectionSelector`; it may have been from looking at [atom/language-todo](https://github.com/atom/language-todo).

**Comment by pchaigno** [comment]
Ok. Thanks for the pointers!
