### ISSUE TITLE
Adding Jison to GitHub Linguist

### ISSUE THREAD

**Issue by nwhetsell** [cdibbs/language-jison#5]
What are your thoughts on adding language-jison to [GitHub Linguist](https://github.com/github/linguist) so that GitHub highlights Jison files? I’ve prepared a [fork](https://github.com/nwhetsell/linguist/commit/711a5fe8818d48be28a9718e72c0f4ae499f5576) of Linguist that includes Jison, and I’d be happy to open this pull request over at Linguist:

> This pull request adds grammars and supporting files for [Jison](https://zaa.ch/jison/). A [search for files with a jison extension](https://github.com/search?utf8=✓&q=extension%3Ajison+NOT+nothack&type=Code&ref=searchresults) shows 2,000+ code results, and a [search for files with a jisonlex extension](https://github.com/search?utf8=✓&q=extension%3Ajisonlex+NOT+nothack&type=Code&ref=searchresults) shows 1,000+ code results. The samples are from https://github.com/zaach/jison, which is [MIT-licensed](https://github.com/zaach/jison#license), and https://github.com/GerHobbelt/jison, which is also [MIT-licensed](https://github.com/GerHobbelt/jison#license).

**Comment by cdibbs** [comment]
Yeah, please feel free! That seems justifiable given jison's usage in higher-profile projects like CoffeeScript.

**Comment by nwhetsell** [comment]
[Done](https://github.com/github/linguist/pull/3488).
